### ISSUE TITLE
Cannot find module 'knex/lib/transaction'

### ISSUE THREAD

**Issue by anish-techpro** [markusahlstrand/knex-data-api-client#54]
The following versions are used:
"knex": "^0.95.4",
"knex-aurora-data-api-client": "^1.5.2",

When i am deploying the code in lambda and calling the api the following error is what I get:

Cannot find module 'knex/lib/transaction'.

**Comment by markusahlstrand** [comment]
There seems to have been a pretty big leap in the knex versions. It went from 0.21 last month straight to 0.95 now.. Not sure what happened?

Try using this version and see if it works:
"knex": "0.21.1"

**Comment by markusahlstrand** [comment]
From gitter:

```
Christophe Geers @geersch Mar 27 11:52
Hi, got a small question. What's the reasoning behind the version jump from 0.21.x to 0.95.x. Why not 0.22.x, every minor update below major version 1 indicates breaking changes. Does the 0.95.xalign with something else or is it just a random choice? Thanks.

Igor Savin @kibertoad Mar 27 13:02
It indicates how close we are to 1.0.0 :). And larger than usual amount of breaking changes.
```

I'll try to update the knex reference and see if there's something we need to patch.

**Comment by anish-techpro** [comment]
@markusahlstrand we have tried using knex: 0.21.1 but it is getting Time out error, and we have started our project using knex:0.95 and we have progressed a lot so it would be better if you could update the package to work with knex:0.95.

**Comment by markusahlstrand** [comment]
Yepp, will try to update and see if the tests pass.

**Comment by markusahlstrand** [comment]
Published 1.5.3 now with updated packages. Could you check if it's still an issue?

**Comment by jonathannen** [comment]
This version still generates the same error with `0.95.x` versions of Knex.

Believe the require now needs to be: `const Transaction = require('knex/lib/execution/transaction');`.

This solves the issue, but brings up other match-matches to the new Knex API.

**Comment by markusahlstrand** [comment]
Could you share a snippet of the code that isn't working for you? We have a integration-test in the project for transactions (https://github.com/markusahlstrand/knex-data-api-client/blob/master/test/integration/common-tests.js#267) that is passing. Are you managing transactions in a different way?

**Comment by jonathannen** [comment]
@markusahlstrand Here is a small repo that demonstrates it: https://github.com/jonathannen/knex-aurora-data-api-client-54

This is using `"knex": "^0.95.4",` and `"knex-aurora-data-api-client": "^1.5.3"`. If you run the `index.js` it'll generate:

```Error: Cannot find module 'knex/lib/transaction'
Require stack:
- /Users/jon/Code/knex-aurora-data-api-client-issue/node_modules/knex-aurora-data-api-client/src/data-api-transaction.js
- /Users/jon/Code/knex-aurora-data-api-client-issue/node_modules/knex-aurora-data-api-client/src/data-api.js
- /Users/jon/Code/knex-aurora-data-api-client-issue/node_modules/knex-aurora-data-api-client/src/postgres.js
- /Users/jon/Code/knex-aurora-data-api-client-issue/node_modules/knex-aurora-data-api-client/index.js
- /Users/jon/Code/knex-aurora-data-api-client-issue/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/Users/jon/Code/knex-aurora-data-api-client-issue/node_modules/knex-aurora-data-api-client/src/data-api-transaction.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/Users/jon/Code/knex-aurora-data-api-client-issue/node_modules/knex-aurora-data-api-client/src/data-api.js:8:28)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jon/Code/knex-aurora-data-api-client-issue/node_modules/knex-aurora-data-api-client/src/data-api-transaction.js',
    '/Users/jon/Code/knex-aurora-data-api-client-issue/node_modules/knex-aurora-data-api-client/src/data-api.js',
    '/Users/jon/Code/knex-aurora-data-api-client-issue/node_modules/knex-aurora-data-api-client/src/postgres.js',
    '/Users/jon/Code/knex-aurora-data-api-client-issue/node_modules/knex-aurora-data-api-client/index.js',
    '/Users/jon/Code/knex-aurora-data-api-client-issue/index.js'
  ]
}
```

If you change the `data-api-transaction.js` require from `knex/lib/transaction` to `knex/lib/execution/transaction` this fixes the error above. However, this then generates:

```
/Users/jon/Code/knex-aurora-data-api-client-issue/node_modules/knex-aurora-data-api-client/src/postgres.js:7
  PostgresClient.call(this, config);
                 ^

TypeError: Class constructor Client_PG cannot be invoked without 'new'
    at new PostgresClientRDSDataAPI (/Users/jon/Code/knex-aurora-data-api-client-issue/node_modules/knex-aurora-data-api-client/src/postgres.js:7:18)
    at knex (/Users/jon/Code/knex-aurora-data-api-client-issue/node_modules/knex/lib/knex-builder/Knex.js:12:28)
    at Object.<anonymous> (/Users/jon/Code/knex-aurora-data-api-client-issue/index.js:13:1)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

Solution there appears to be to change `PostgresClient.call(this, config);` to `return new PostgresClient(config)`. I assume it's a similar situation with MySQL.

**Comment by markusahlstrand** [comment]
Hi, do you get this error by just trying to instantiate knex or is it when trying to run an actual query?

I'm thinking if it's matter of not having access to the database at AWS?

**Comment by jonathannen** [comment]
@markusahlstrand that first error is from the example repo: https://github.com/jonathannen/knex-aurora-data-api-client-54 -- that's not from instantiation or query. Just from `require("knex-data-api-client")`. Yarn/Npm install and run `index.js` to see the output.

In knex `0.95.x` the transaction file being required in `knex-data-api-client` has moved.

The second error is when I shim the require from `knex/lib/transaction` to `knex/lib/execution/transaction`.

**Comment by adampotocki** [comment]
Any updates on the fix to these issues?

**Comment by markusahlstrand** [comment]
I'll have a look at it today..

**Comment by markusahlstrand** [comment]
Ok, so it seems that the transaction class was moved into the execution folder in the 0.95 release.

Had a look at the Objection repo and they simply won't support the 0.95 release for now and wait until the 1.0.0 release is done which might be 6 months away.

Knex also changed to use classes rather than functions for the Postgres and MySql client, so that needs to update as well. 

Think there's two ways to solve it, either we keep separate versions for the 0.21 and the 0.95 version of knex. Or.. we do some checks to see which version we're on. I think I'll go ahead and add the checks for now to keep it simple.

**Comment by markusahlstrand** [comment]
Published 1.5.4 that should solve this issue. Let me know if it works for you

**Comment by anish-techpro** [comment]
> Had a look at the Objection repo and they simply won't support the 0.95 release for now and wait until the 1.0.0 release is done which might be 6 months away.

@markusahlstrand In the following issue Sami Koskimäki mentioned that Objection 3.0 is going to support knex 0.95 and he is working on it.

https://github.com/Vincit/objection.js/issues/2012

**Comment by markusahlstrand** [comment]
Ok, sounds good. The 1.5.4 version should support knex 0.95, so as soon as the 3.0 version of Objection is released you should be good to go.

Is there anything else that needs to be fixed on my end or can I go ahead and close this issue?

**Comment by anish-techpro** [comment]
@markusahlstrand it is working now, thanks
